# Generated by Django 4.2.2 on 2023-07-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='postimg_def.jpg', upload_to='Posts_pics/%y/%m/%d'),
        ),
    ]
