# Generated by Django 4.2.2 on 2023-07-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categry',
            field=models.CharField(choices=[('Development', 'Development'), ('Ethical Hacking', 'Ethical Hacking'), ('Marketing', 'Marketing'), ('Info', 'Info'), ('general topic', 'general topic')], default='general topic', max_length=50),
        ),
    ]
