# Generated by Django 4.2.2 on 2023-07-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_categry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='postimg_def.jpg', upload_to='Posts_pics'),
        ),
    ]
